### ISSUE TITLE
Right click for possible orders, left for execution

### ISSUE THREAD

**Issue by itamarLaufer** [itamarLaufer/SuperTactico#20]
Everywhere, anytime

**Comment by itamarLaufer** [comment]
This issue can be closed if we decide this feature is redundant after moving to drag and drop gestures.
@RoniJacobson  , express your opinion please.

**Comment by RoniJacobson** [comment]
I don't think we should close it.
1. It is still relevant to the tkinter implementation of the GUI.
2. I am not sure we should entirely abandon the option to click on a piece and then on the tile you want to move it to in pyside.
