### ISSUE TITLE
loading theoretical engine issues

### ISSUE THREAD

**Issue by itamarLaufer** [itamarLaufer/SuperTactico#22]
When a piece loads piece which load other pieces - those loaded pieces become being loaded by the loader of their loader?

**Comment by RoniJacobson** [comment]
I thought that a piece that has pieces loaded cannot be loaded

**Comment by itamarLaufer** [comment]
> I thought that a piece that has pieces loaded cannot be loaded

After deep thinking it would be the best.
You can load one unloading piece each turn (unless it has the flag) but you can load piece that is loaded.

**Comment by RoniJacobson** [comment]
I don't understand what you mean.
