### ISSUE TITLE
Rules error

### ISSUE THREAD

**Issue by RoniJacobson** [itamarLaufer/SuperTactico#23]
The rules seem to say that a plane may only be placed on the sea in the beginning of the game
![](https://i.imgur.com/EhKSQdK.jpg)
But the server allows it to be both on land and on sea.

**Comment by itamarLaufer** [comment]
It seems that your'e right. It won't be easy to fix.

**Comment by itamarLaufer** [comment]
It's done on itamar and will be merged into master soon.
