### ISSUE TITLE
Movement issues

### ISSUE THREAD

**Issue by RoniJacobson** [itamarLaufer/SuperTactico#26]
When two pieces are near each other, the movment breaks a bit. 
I am not sure what exactly causes it, but I will include several screenshots
![image](https://user-images.githubusercontent.com/36922833/57616556-18e1d980-7587-11e9-8a0a-e77e365cd2b0.png)
![image](https://user-images.githubusercontent.com/36922833/57616636-49c20e80-7587-11e9-97d8-07954033bad3.png)
![image](https://user-images.githubusercontent.com/36922833/57616660-5b0b1b00-7587-11e9-9b12-3e34e64a0093.png)
![image](https://user-images.githubusercontent.com/36922833/57616705-7b3ada00-7587-11e9-9687-e239865b6e1d.png)

**Comment by itamarLaufer** [comment]
Is the purple square connected to the bug?
If so, then what does it stand for?

**Comment by RoniJacobson** [comment]
The purple square is where the mouse currently is. It has nothing to do with the bug
