### ISSUE TITLE
simple chat - engine support

### ISSUE THREAD

**Issue by itamarLaufer** [itamarLaufer/SuperTactico#34]
The message ID is 8 (in both client and server side).
the format is `8_{message}` for instance, `8_Nice move man! but I'm still gonna win😏`
A message can be sent in each moment of the game no matter which player turn it is (From the moment the player is connected to another player).

Gui support is needed.
P.S The GUI should use the name sent in the connection message to present the chat like this:

> Alice: Hi
> Bob: Are you ready to play?
> Bob: Ahh?
(Maybe the time each message was sent at should also be presented.)

**Comment by RoniJacobson** [comment]
Noting that at least in the qt version the chat is presented in bubbles and not as suggested here
