### ISSUE TITLE
Get placeholder pictures

### ISSUE THREAD

**Issue by RoniJacobson** [itamarLaufer/SuperTactico#9]
We need pictures to use as the tiles. Later on we will need better pictures, but for now we need placeholder images.

**Comment by RoniJacobson** [comment]
The images are **way** too big. we need images that are closer to maybe 40x40 at most, not 302x302

**Comment by itamarLaufer** [comment]
Can't you just determine the size of the images when they are put on the screen?
I actually have a script which resizes images but it sounds odd that we need to use it.

**Comment by RoniJacobson** [comment]
I tried that. The issue is that because the images are much to big originaly, when I shrink them down you can no longer read them.

**Comment by RoniJacobson** [comment]
@itamarLaufer I tried that. The issue is that because the images are much to big originaly, when I shrink them down you can no longer read them.

**Comment by itamarLaufer** [comment]
Images indeed should have been much smaller but because these are temporary for debugging we will stick with them.
